### PR TITLE
Add igdb.com to Göteborg

### PR DESCRIPTION
**Pull request by krazyjakee**

### CODE REVIEW

**Comment by olleolleolle** [comment]
This seems like something which does not inform the reader about Rails-using companies or organizations in Sweden. Perhaps we can close this PR.

**Comment by krazyjakee** [comment]
Looks like I misunderstood this page. My apologies.

**Comment by himynameisjonas** [comment]
> This seems like something which does not inform the reader about Rails-using companies or organizations in Sweden. Perhaps we can close this PR.

I think IGDB is a Rails-using company based in Göteborg (but owned by Twitch), at least according to [their job ad](https://boards.greenhouse.io/twitch/jobs/4821264002)

**Comment by krazyjakee** [comment]
Yes, to be clear, I work for IGDB and this was me putting IGDB on a list of companies that use rails (which we do). The page title mentions teams so I was thinking that is perhaps different from a company.

**Comment by olleolleolle** [comment]
Aha! Grand, that makes much more sense, @krazyjakee! Since the change wasn't accompanied by any description, I was merely confused. Personally, then, I am glad to have you on the list. 🎉

**Comment by krazyjakee** [comment]
Awesome! Sorry for the confusion.

**Pull request merged**
