### PR TITLE
Bump jekyll to a version that has kramdown as dependency

### PR DESCRIPTION
**Pull request by peterlind**
The jekyll verision in `Gemfile.lock` on `master` wont start due to missing kramdown as a dependency

### CODE REVIEW

**Comment by teoljungberg** [comment]
I'm unsure how to test this out, to verify that everything is working with the GitHub pages integration. Could @henrik shed some light on that?

**Comment by peterlind** [comment]
I think the pages are built and served with the version Github chooses. The version in `Gemfile.lock` only applies when you run locally

**Comment by henrik** [comment]
No idea I'm afraid!

**Comment by martinholmin** [comment]
Wouldn't using the github-pages gem solve this. It's supposed to be in sync with the version github uses.

https://github.com/github/pages-gem

**Comment by dentarg** [comment]
Let's go with #36 instead.

**Pull request closed without merging**
